

knife4j:
  enable: false
  setting:
    language: zh_cn


# swagger 页面访问： http://localhost:${server.servlet.context-path}/doc.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    # 分组信息也可以在这里配置，在代码的配置类里面配置也是可以的。
    - group: 'task-manager'
      paths-to-match:
        - "/task/manager/**"
      packages-to-scan:
        - "com.suyh.metric.controller"
    - group: 'flink-cluster-env'
      paths-to-match:
        - "/flink/cluster/env/**"
      packages-to-scan:
        - "com.suyh.metric.controller"

---
spring:
  config:
    activate:
      on-profile: suyh

knife4j:
  enable: true


