logging:
  level:
    root: info
    # com.baomidou.mybatisplus.extension.toolkit.Db: error
  file:
    name: /tmp/logs/mock/mock.log
  logback:
    rollingpolicy:
      file-name-pattern: /tmp/logs/mock/%d{yyyy-MM-dd}/mock.%03i.log

---
spring:
  config:
    activate:
      on-profile: suyh

logging:
  level:
    root: info


